### PR TITLE
feat: Introduce option to delete enrollment requests that are denied/revoked

### LINKED ISSUE #628: at_activate being able to delete denied entries in `list`
### Is your feature request related to a problem? Please describe.

I have a denied key and would like to delete it from the `list`

Currently there is no way to delete entries..

### Describe the solution you'd like

```
╰$ at_activate interactive -a @ssh_1
Connecting ... Connected
$ list
Found 1 matching enrollment records
Enrollment ID                         Status    AppName             DeviceName                            Namespaces
707a70e6-ff19-4a46-82c1-9c7cde186039  denied    sshnp               orac_ssh_1                            {sshnp: rw, sshrvd: rw}
$ delete -i 707a70e6-ff19-4a46-82c1-9c7cde186039
$ list
Found 0 matching enrollment records
Enrollment ID                         Status    AppName             DeviceName                            Namespaces

```

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by srieteja**
Closes https://github.com/atsign-foundation/at_libraries/issues/628

**- What I did**
- Introduce an option to allow deletion of enrollment requests (for denied/revoked enrollments only)

**- How I did it**
- Introduced 'delete' as an option in the at_activate argParser
- Introduced a delete-command parser which considers enrollmentId mandatory
- Introduce a new method deleteDeniedEnrollment which sends a delete request to the server and parses the server response.

**- How to verify it**
- Manual testing has been done. 
- To test the changes, send an enrollment request then deny/approve+revoke it. Then run at_activate with the delete option which requires the atsign and enrollmentId. The enrollment should be deleted.

### CODE REVIEW

**Comment by gkc** [comment]
@srieteja @sitaram-kalluri Is this blocked by something?

**Comment by srieteja** [comment]
> @srieteja @sitaram-kalluri Is this blocked by something?

I was waiting for the server-side changes to be released. Server-side changes were released by @sitaram-kalluri last week. I will test this again and get it ready for review over the coming weekend.

**Comment by gkc** [comment]
@srieteja You should stay focused on the C impl of at_activate.
@sitaram-kalluri can you pick this up please?

**Comment by sitaram-kalluri** [comment]
> @srieteja You should stay focused on the C impl of at_activate.
> @sitaram-kalluri can you pick this up please?

@gkc : Sure, I will pick this up.

**Comment by sitaram-kalluri** [comment]
Tested the deletion of enrollment and works as expected. Attaching the test log:

Deleting a revoked enrollment:

```
sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ dart activate_cli.dart revoke -a @alice🛠 -r vip.ve.atsign.zone -k ~/.atsign/keys/\@alice🛠_key.atKeys -i 19f571bb-25a7-409d-80cb-984f2bc882a6
Connecting ... Connected
Revoking enrollmentId 19f571bb-25a7-409d-80cb-984f2bc882a6
Server response: data:{"status":"revoked","enrollmentId":"19f571bb-25a7-409d-80cb-984f2bc882a6"}

sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ dart activate_cli.dart delete -a @alice🛠 -r vip.ve.atsign.zone -k ~/.atsign/keys/\@alice🛠_key.atKeys -i 19f571bb-25a7-409d-80cb-984f2bc882a6
Connecting ... Connected
Sending delete request
Server response: {"enrollmentId":"19f571bb-25a7-409d-80cb-984f2bc882a6","status":"deleted"}
sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ 

```

Deleting a denied enrollment:

```
sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ dart activate_cli.dart deny -a @alice🛠 -r vip.ve.atsign.zone -k ~/.atsign/keys/\@alice🛠_key.atKeys -i 6458cf5d-7a92-4404-a460-412a2f7ac08b
Connecting ... Connected
Denying enrollmentId 6458cf5d-7a92-4404-a460-412a2f7ac08b
Server response: data:{"status":"denied","enrollmentId":"6458cf5d-7a92-4404-a460-412a2f7ac08b"}

sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ dart activate_cli.dart delete -a @alice🛠 -r vip.ve.atsign.zone -k ~/.atsign/keys/\@alice🛠_key.atKeys -i 6458cf5d-7a92-4404-a460-412a2f7ac08b
Connecting ... Connected
Sending delete request
Server response: {"enrollmentId":"6458cf5d-7a92-4404-a460-412a2f7ac08b","status":"deleted"}
```

**Comment by gkc** [comment]
@sitaram-kalluri Let's also wait to release this until [this bug fix](https://github.com/atsign-foundation/at_server/pull/2117) has been released

**Comment by gkc** [comment]
@sitaram-kalluri I am going to merge this PR's changes into https://github.com/atsign-foundation/at_libraries/pull/682 since they are all related and I've made a number of changes in #682 related to the tests

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri I am going to merge this PR's changes into #682 since they are all related and I've made a number of changes in #682 related to the tests

Sure, @gkc

**Comment by gkc** [comment]
All of this PR's commits are now included in #682

**Comment by gkc** [comment]
Marked as draft since all of this PR's changes are now entirely included in #682

**Pull request merged**
