### PR TITLE
fix: Add unrevoke to the at_onboarding_cli

### LINKED ISSUE #627: at_activate adding option to un-revoke/enable revoked atKeys
### Is your feature request related to a problem? Please describe.

Not really a problem but it would be nice to be able to revoke access and when needed unrevoke/enable a set of keys via at_activate.
This would for example allow an sshnpd to not authenticate until the atKey is re-enabled. Further adding a security layer for example. Simimalr to the idea of the Policy plane its a sort of poor mans policy plane.

### Describe the solution you'd like

Add command to re-enable entries like the one below..

```
s
Enrollment ID                         Status    AppName             DeviceName                            Namespaces
707a70e6-ff19-4a46-82c1-9c7cde186039  denied    sshnp               orac_ssh_1                            {sshnp: rw, sshrvd: rw}
$
```

### Describe alternatives you've considered

I do wonder about language as well..

revoke/unrevoke - unrevoked becomes enabled in `list` ?
disable/enable 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
Closes #627 and #628

This PR includes everything from #670 

**- What I did**
- Add "unrevoke" to auth_cli commands which will restore the revoked enrollmentId.
- Add "delete" to auth_cli commands which will permanently delete enrollment requests (only denied/revoked enrollments may be deleted)
- Made various changes (replacing `exit` with `throw`, etc) to ensure that the tests in enrollment_cli_commands_test.dart behave as they should

**- How I did it**
- Introduced 'delete' as an option in the at_activate argParser
- Introduced a delete-command parser which considers enrollmentId mandatory
- Introduce a new method deleteDeniedEnrollment which sends a delete request to the server and parses the server response.
- Add "unrevoke" command to auth_cli_args list.
- Add "unrevoke" method in auth_cli which will do the necessary work to unrevoke the enrollment Id.

**- How to verify it**
- Added an End-to-End test in "enrollment_cli_commands_test.dart" file which covers unrevoke functionality.
- Manual testing has been done. 
- To test the changes, send an enrollment request then deny/approve+revoke it. Then run at_activate with the delete option which requires the atsign and enrollmentId. The enrollment should be deleted.

### CODE REVIEW

**Comment by sitaram-kalluri** [comment]
The functional tests in at_onboarding_cli are failing due to "enrollment_cli_commands_test.dart", which requires the unrevoke functionality on the secondary server in production. Currently, the unrevoke feature is only available in the canary.

**Comment by gkc** [comment]
@sitaram-kalluri when are you planning to promote canary to prod?

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri when are you planning to promote canary to prod?

@gkc : We released the latest version to canary last week? Shall we do a prod release today ?

**Comment by gkc** [comment]
Yes; I will do a prod release now

**Comment by gkc** [comment]
@sitaram-kalluri Or - does [this bug fix](https://github.com/atsign-foundation/at_server/pull/2117) need to go out to canary first?

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri Or - does [this bug fix](https://github.com/atsign-foundation/at_server/pull/2117) need to go out to canary first?

@gkc : Yeah, Let us first release the bug fix to canary and then do a prod release.

**Comment by gkc** [comment]
@sitaram-kalluri FYI please review the changes I've made in my last few commits starting with [this one](https://github.com/atsign-foundation/at_libraries/pull/682/commits/5407f7f25ddfbaec47eb3e86a70ae0a3e39e75f3)

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri FYI please review the changes I've made in my last few commits starting with [this one](https://github.com/atsign-foundation/at_libraries/pull/682/commits/5407f7f25ddfbaec47eb3e86a70ae0a3e39e75f3)

Sure Gary

**Comment by gkc** [comment]
Marking as draft until [this PR](https://github.com/atsign-foundation/at_server/pull/2117) has been completed, reviewed, merged and released first to canary and then to prod

**Comment by sitaram-kalluri** [comment]
> Marking as draft until [this PR](https://github.com/atsign-foundation/at_server/pull/2117) has been completed, reviewed, merged and released first to canary and then to prod

The changes are released into the prod with version at_secondary_server v3.0.51. All the functional tests are passing now and therefore, marking the PR ready for review.

**Review by gkc — APPROVED** [review]
LGTM. Thanks @srieteja and @sitaram-kalluri

**Comment by gkc** [comment]
@sitaram-kalluri Can you review, approve and merge this please, as I was the last committer.

**Review by murali-shris — APPROVED** [review]

**Pull request merged**
