### PR TITLE
feat: Onboarding cli uptake atchops

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
- Uptake at_chops in onboarding cli
- minor code refactoring
**- How I did it**
- in the authenticate method, once key pairs are created in local secondary, create an at_chops instance and set it to atClient and  atLookUp instance
- added default getters and setters for atClient and atLookUp
- deprecate getAtClient() method and moved the logic to _init method
- minor code refactoring in _readAtKeysFile, getSecretFromQr methods
- added a new unit test at_onboarding_cli_test.dart
**- How to verify it**
- run the unit and functional test

### CODE REVIEW

**Review by gkc — CHANGES_REQUESTED** [review]
Can you verify at_talk runs successfully if it uses this branch please Murali?

**Comment by murali-shris** [comment]
> Can you verify at_talk runs successfully if it uses this branch please Murali?

Auth is failing in during initial sync in at_talk.

sync_service_impl.dart
 static Future<SyncService> create(AtClient atClient,
      {required AtClientManager atClientManager,
      required NotificationService notificationService,
      RemoteSecondary? remoteSecondary}) async {
    remoteSecondary ??= RemoteSecondary(
        atClient.getCurrentAtSign()!, atClient.getPreferences()!); 
        //atLookUp for this remote secondary gets the private key from preferences in previous logic. In latest changes we have removed setting private key in preferences from onboarding flow. Have to think of a logic to set atChops to the remote secondary of SyncService. We will face the same issue in at_client also when we remove private key from preferences.

**Comment by gkc** [comment]
So ... optional atChops parameter for RemoteSecondary constructor?

**Comment by murali-shris** [comment]
> So ... optional atChops parameter for RemoteSecondary constructor?

but at the time SyncService instance creation, atChops instance will not be available since keys are not yet available in local secondary.

**Comment by gkc** [comment]
@murali-shris

* I've [made changes to the at_client package](https://github.com/atsign-foundation/at_client_sdk/pull/887) which enable this issue to be resolved and have added that branch as dependency override for at_client for this PR
* I've [made changes in this branch](https://github.com/atsign-foundation/at_libraries/pull/281/commits/9cf6f3373aab8d03484d9fef369e9d290fcead60) to take up those at_client changes
* Finally, I've added this branch and the at_client branch as dependency overrides to my branch of at_talk which now works without error when useAtChops is set to true

**Comment by gkc** [comment]
at_client PR has been merged and version 3.0.52 has been published. Have removed the dependency_overrides for at_client from this PR. All looks good, will merge to trunk.

**Review by gkc — APPROVED** [review]

**Pull request merged**
