### PR TITLE
fix: do not store pkamPublicKey, encryptionPublicKey on LocalSecondary

### LINKED ISSUE #1075: at_client expects internal keys to have namespace (when namespace is not provided through preferences)
### Describe the bug

some atsigns after being activated with activate_cli/onboarding_cli end up in a situation where sync keeps failing due to an exception 
````
SEVERE|2023-06-26 13:34:51.888723|SyncService (@34thundering)|Exception in sync cb049548-7780-4cf0-95c1-7bde8faa1d93. Reason: Failed to syncData caused by namespace is mandatory 
````

When a namespace is not set through at_client preferences, at_client while creating internal keys (e.g. lastReceivedCommitId, lastReceivedNotification) expects a namespace explicitly defined for these keys. And since these keys do not have a specific namespace, the client throws an exception which terminates the client.

### Steps to reproduce

1. First I 'activate a new atsign with activate_cli'
2. Then I 'use that atsign with onboaring_cli'
3. And then 'insert a key into the local secondary'
4. This results in a Sync Failure and the syncs keep failing forever

### Expected behavior

Sync should succeed and not throw any exceptions

### Possible solution

1. exclude internal keys from the namespace scrutiny (possibly in the validatePutRequest() in at_client_impl)
2. use a constant/predefined namespace for all internal keys

### Were you using an atApplication when the bug was found?

AtOnbaordingCli

### PR DESCRIPTION
**Pull request by srieteja**
partially resolves https://github.com/atsign-foundation/at_client_sdk/issues/1075

**- What I did**
- Resolve sync conflict caused by encryptionPublicKey
- Make namespace mandatory for authentication

**- How I did it**
- do not insert pkamPublicKey and encryptionPublicKey into LocalSecondary
- throw an exception when namespace is not provided during authentication

**- How to verify it**
- test yet to come

**- Description for the changelog**

- Make namespace mandatory for authentication

### CODE REVIEW

**Comment by murali-shris** [comment]
@srieteja Please revisit these changes after we complete client side changes for APKAM

**Comment by srieteja** [comment]
> @srieteja Please revisit these changes after we complete client side changes for APKAM

Will do @murali-shris

**Comment by gkc** [comment]
> > @srieteja Please revisit these changes after we complete client side changes for APKAM
> 
> Will do @murali-shris

@srieteja @murali-shris  Is it time to revisit this PR?

**Comment by srieteja** [comment]
This was supposed to be a solution for a bug we had in the past, but we found a better solution. This is not relevant anymore.

**Comment by gkc** [comment]
> This was supposed to be a solution for a bug we had in the past, but we found a better solution. This is not relevant anymore.

Excellent, thanks @srieteja

**Pull request closed without merging**
