### PR TITLE
Quick fix at_lookup race condition

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
* Added use of a mutex into `AtLookupImpl._process()` to prevent race condition which surfaced during testing the mwc_demo end-to-end

**- How I did it**
* Added dependency on mutex package
* Created a Mutex for use by `_process()`; modified `_process()` to acquire the mutex to start with, and release it in a `finally` block

**- How to verify it**
* DONE: Verified this fixed the issue for mwc_demo
* DONE: Run all tests in `at_client_sdk` with a dependency override for at_lookup to this branch
* DONE: test atmospherepro with this branch
* DONE: [Added a test to at_client_sdk/at_functional_test](https://github.com/atsign-foundation/at_client_sdk/pull/408). (To see the test failing, add `at_lookup: 3.0.7` to at_client_sdk/at_functional_test/pubspec.yaml)

**- Description for the changelog**
* Added use of a mutex into `AtLookupImpl._process()` to prevent race condition

### CODE REVIEW

**Comment by gkc** [comment]
@murali-shris Please review at your earliest convenience; given the severity of this bug, I'd like to merge to trunk asap - ideally tomorrow

I will add extra tests tomorrow morning (unit tests for at_lookup, as well as an end-to-end test)

In the interim, @purnimavenkatasubbu it would be great if you could **locally** run all of the tests in `at_client_sdk`, and maybe test AtmosherePro as well, in order to verify that this doesn't break something else. You will need 
```
dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: quickFixAtLookupRaceCondition
```

**Comment by gkc** [comment]
Issue documented at https://github.com/atsign-foundation/at_libraries/issues/140

**Review by murali-shris — APPROVED** [review]

**Review by VJag — APPROVED** [review]

**Comment by purnimavenkatasubbu** [comment]
Verified functional_tests of client_sdk locally and verified @mosphere_pro app pointing to the following in dependency_overrides
at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: quickFixAtLookupRaceCondition
      
   Did not face any issues. Attaching POT's 
[atLookupTestLogs.txt](https://github.com/atsign-foundation/at_libraries/files/8087791/atLookupTestLogs.txt)

@mosphere_pro app recordings

https://user-images.githubusercontent.com/43639593/154457770-ddab3dfc-e03e-4700-af2b-7a731bb355fc.mp4

https://user-images.githubusercontent.com/43639593/154457787-966dcc48-882f-452d-a0ad-673f97144c55.mp4

https://user-images.githubusercontent.com/43639593/154458088-9b5abd87-0a3d-4222-8068-41be54ff8006.mp4

**Comment by gkc** [comment]
Thanks Purnima, great!

**Pull request merged**
